version: 2.1

orbs:
  maven: circleci/maven@1.0.1
  node: circleci/node@3.0.1

jobs:
  setup:

    docker: 
      - image: circleci/openjdk:8-jdk-stretch   

    - checkout:
          path: ~/card-games

  build_server: 

    working_directory: ~/card-games/server

    steps:
      
      - restore_cache: 
          
          key: card-games-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache: 
          paths:
            - ~/.m2
          key: card-games-{{ checksum "pom.xml" }}
      
      - run: mvn package 