version: 2.1

orbs:
  maven: circleci/maven@0.0.12
  cypress: cypress-io/cypress@1.25.1
  sonarcloud: sonarsource/sonarcloud@1.0.1

executors:
  cypress-chrome:
    docker:
      - image: "cypress/browsers:node12.14.1-chrome83-ff77"
    environment:
      CYPRESS_TEST_ENV: PRODUCTION
      CYPRESS_baseUrl: https://card-games-tcc.herokuapp.com

jobs:
  server:
    working_directory: ~/card-games/server

    docker:
      - image: circleci/openjdk:11.0-jdk-stretch

    steps:
      - checkout:
          path: ~/card-games

      - restore_cache:
          key: card-games-server-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: card-games-server-{{ checksum "pom.xml" }}

      - run:
          name: Run unit tests
          command: mvn test

      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar

  webapp:
    working_directory: ~/card-games/webapp

    docker:
      - image: circleci/node:stretch

    steps:
      - checkout:
          path: ~/card-games

      - restore_cache:
          keys:
            - card-games-webapp-{{ checksum "package.json" }}

      - save_cache:
          paths:
            - node_modules
          key: card-games-webapp-{{ checksum "package.json" }}

      - run: npm install

      - run: npm test a -- --coverage

      - sonarcloud/scan

  package:
    working_directory: ~/card-games/server

    docker:
      - image: circleci/openjdk:11.0-jdk-stretch

    steps:
      - checkout:
          path: ~/card-games

      - run: mvn clean install -DskipTests -P package

      - run: ls target | grep server.*jar$ | xargs -I{} mv target/{} target/server.jar

      - store_artifacts:
          path: target/server.jar

      - persist_to_workspace:
          root: .
          paths:
            - target/server.jar

  deploy:
    machine:
      enabled: true

    working_directory: ~/card-games

    environment:
      HEROKU_APP_NAME: card-games-tcc

    steps:
      - checkout

      - run: bash .circleci/setup-heroku.sh

      - run: heroku plugins:install java

      - attach_workspace:
          at: server

      - run: heroku deploy:jar server/target/server.jar --app $HEROKU_APP_NAME

  api-test:
    working_directory: ~/card-games/api-integration-tests

    docker:
      - image: circleci/openjdk:11.0-jdk-stretch

    environment:
      TEST_ENV: PRODUCTION

    steps:
      - checkout:
          path: ~/card-games

      - restore_cache:
          key: card-games-api-test-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: card-games-api-test-{{ checksum "pom.xml" }}

      - run: mvn test

workflows:
  version: 2
  build:
    jobs:
      - server:
          context: SONAR_CLOUD_SERVER
      - webapp:
          context: SONAR_CLOUD_WEBAPP
      - package:
          requires:
            - server
            - webapp
      - deploy:
          requires:
            - package
      - api-test:
          requires:
            - deploy
      - cypress/run:
          name: webapp-tests
          working_directory: app-integration-tests
          executor: cypress-chrome
          browser: chrome
          cache-key: >-
            card-games-webapp-test-{{ checksum "app-integration-tests/package.json"
            }}
          requires:
            - deploy
